import hashlib
import json
from dataclasses import dataclass, field
from pathlib import Path
from typing import Optional


REPO_ROOT = Path(__file__).resolve().parent.parent.parent


@dataclass
class GoldenDesign:
    name: str
    top_module: str
    pdk: str
    clock_period_ns: float
    design_type: str
    expected_qor: float
    expected_wns: float
    expected_tns: float
    expected_utilization: float
    expected_cell_count: int
    base_metrics: dict  # Synthetic baseline metrics for injection
    manifest_path: str
    tags: list[str] = field(default_factory=list)

    @property
    def fingerprint(self) -> str:
        raw = f"{self.name}:{self.top_module}:{self.clock_period_ns}:{json.dumps(self.base_metrics, sort_keys=True)}"
        return hashlib.sha256(raw.encode()).hexdigest()[:16]


GOLDEN_DESIGNS: list[GoldenDesign] = [
    GoldenDesign(
        name="counter",
        top_module="counter",
        pdk="sky130A",
        clock_period_ns=10.0,
        design_type="tiny",
        expected_qor=0.86,
        expected_wns=0.05,
        expected_tns=0.0,
        expected_utilization=15.0,
        expected_cell_count=100,
        base_metrics={
            "setup_wns_ns": 0.05, "setup_tns_ns": 0.0,
            "hold_whs_ns": 0.02, "hold_ths_ns": 0.0,
            "utilization": 15.0, "cell_count": 100,
            "runtime_sec": 42.0, "qor_score": 0.86,
            "overflow_h": 0.01, "overflow_v": 0.01,
            "drc_total_violations": 0, "drc_is_clean": True,
            "lvs_status": "PASS", "lvs_return_code": 0,
            "power_ir_drop_pct": 2.0,
            "clock_skew_ns": 0.1,
            "max_transition_ns": 0.3,
            "max_capacitance_pf": 0.1,
            "implementation_status": "SUCCESS",
            "signoff_status": "PASS",
            "tapeout_ready": True,
            "has_sram_macros": False,
        },
        manifest_path="examples/counter/gli_manifest.yaml",
        tags=["tiny", "combinatorial", "sky130"],
    ),
    GoldenDesign(
        name="gcd",
        top_module="gcd",
        pdk="sky130A",
        clock_period_ns=10.0,
        design_type="tiny",
        expected_qor=0.82,
        expected_wns=0.02,
        expected_tns=0.0,
        expected_utilization=20.0,
        expected_cell_count=200,
        base_metrics={
            "setup_wns_ns": 0.02, "setup_tns_ns": 0.0,
            "hold_whs_ns": 0.01, "hold_ths_ns": 0.0,
            "utilization": 20.0, "cell_count": 200,
            "runtime_sec": 45.0, "qor_score": 0.82,
            "overflow_h": 0.01, "overflow_v": 0.01,
            "drc_total_violations": 0, "drc_is_clean": True,
            "lvs_status": "PASS", "lvs_return_code": 0,
            "power_ir_drop_pct": 2.5,
            "clock_skew_ns": 0.08,
            "max_transition_ns": 0.25,
            "max_capacitance_pf": 0.08,
            "implementation_status": "SUCCESS",
            "signoff_status": "PASS",
            "tapeout_ready": True,
            "has_sram_macros": False,
        },
        manifest_path="examples/gcd/gli_manifest.yaml",
        tags=["tiny", "combinatorial", "sky130"],
    ),
    GoldenDesign(
        name="uart",
        top_module="uart_top",
        pdk="sky130A",
        clock_period_ns=10.0,
        design_type="medium",
        expected_qor=0.75,
        expected_wns=-0.1,
        expected_tns=-2.0,
        expected_utilization=35.0,
        expected_cell_count=800,
        base_metrics={
            "setup_wns_ns": -0.1, "setup_tns_ns": -2.0,
            "hold_whs_ns": 0.05, "hold_ths_ns": 0.0,
            "utilization": 35.0, "cell_count": 800,
            "runtime_sec": 90.0, "qor_score": 0.75,
            "overflow_h": 0.02, "overflow_v": 0.02,
            "drc_total_violations": 0, "drc_is_clean": True,
            "lvs_status": "PASS", "lvs_return_code": 0,
            "power_ir_drop_pct": 3.0,
            "clock_skew_ns": 0.15,
            "max_transition_ns": 0.4,
            "max_capacitance_pf": 0.15,
            "implementation_status": "SUCCESS",
            "signoff_status": "PASS",
            "tapeout_ready": True,
            "has_sram_macros": False,
        },
        manifest_path="examples/uart/gli_manifest.yaml",
        tags=["medium", "sequential", "sky130"],
    ),
    GoldenDesign(
        name="gpio",
        top_module="gpio_top",
        pdk="sky130A",
        clock_period_ns=10.0,
        design_type="medium",
        expected_qor=0.78,
        expected_wns=0.0,
        expected_tns=0.0,
        expected_utilization=25.0,
        expected_cell_count=400,
        base_metrics={
            "setup_wns_ns": 0.0, "setup_tns_ns": 0.0,
            "hold_whs_ns": 0.03, "hold_ths_ns": 0.0,
            "utilization": 25.0, "cell_count": 400,
            "runtime_sec": 60.0, "qor_score": 0.78,
            "overflow_h": 0.01, "overflow_v": 0.01,
            "drc_total_violations": 0, "drc_is_clean": True,
            "lvs_status": "PASS", "lvs_return_code": 0,
            "power_ir_drop_pct": 2.0,
            "clock_skew_ns": 0.1,
            "max_transition_ns": 0.3,
            "max_capacitance_pf": 0.1,
            "implementation_status": "SUCCESS",
            "signoff_status": "PASS",
            "tapeout_ready": True,
            "has_sram_macros": False,
        },
        manifest_path="examples/gpio/gli_manifest.yaml",
        tags=["medium", "io", "sky130"],
    ),
    GoldenDesign(
        name="fir",
        top_module="fir_top",
        pdk="sky130A",
        clock_period_ns=10.0,
        design_type="medium",
        expected_qor=0.65,
        expected_wns=-0.5,
        expected_tns=-10.0,
        expected_utilization=45.0,
        expected_cell_count=2000,
        base_metrics={
            "setup_wns_ns": -0.5, "setup_tns_ns": -10.0,
            "hold_whs_ns": 0.1, "hold_ths_ns": 0.0,
            "utilization": 45.0, "cell_count": 2000,
            "runtime_sec": 180.0, "qor_score": 0.65,
            "overflow_h": 0.03, "overflow_v": 0.03,
            "drc_total_violations": 0, "drc_is_clean": True,
            "lvs_status": "PASS", "lvs_return_code": 0,
            "power_ir_drop_pct": 4.0,
            "clock_skew_ns": 0.2,
            "max_transition_ns": 0.5,
            "max_capacitance_pf": 0.2,
            "implementation_status": "SUCCESS",
            "signoff_status": "PASS",
            "tapeout_ready": True,
            "has_sram_macros": False,
        },
        manifest_path="examples/fir/gli_manifest.yaml",
        tags=["medium", "dsp", "sky130"],
    ),
    GoldenDesign(
        name="picorv32",
        top_module="picorv32",
        pdk="sky130A",
        clock_period_ns=20.0,
        design_type="large",
        expected_qor=0.45,
        expected_wns=-2.0,
        expected_tns=-50.0,
        expected_utilization=65.0,
        expected_cell_count=15000,
        base_metrics={
            "setup_wns_ns": -2.0, "setup_tns_ns": -50.0,
            "hold_whs_ns": 0.2, "hold_ths_ns": 0.0,
            "utilization": 65.0, "cell_count": 15000,
            "runtime_sec": 600.0, "qor_score": 0.45,
            "overflow_h": 0.05, "overflow_v": 0.04,
            "drc_total_violations": 0, "drc_is_clean": True,
            "lvs_status": "PASS", "lvs_return_code": 0,
            "power_ir_drop_pct": 5.0,
            "clock_skew_ns": 0.3,
            "max_transition_ns": 0.6,
            "max_capacitance_pf": 0.25,
            "implementation_status": "SUCCESS",
            "signoff_status": "PASS",
            "tapeout_ready": True,
            "has_sram_macros": False,
        },
        manifest_path="examples/picorv32/gli_manifest.yaml",
        tags=["large", "cpu", "sky130"],
    ),
    GoldenDesign(
        name="ibex",
        top_module="ibex",
        pdk="sky130A",
        clock_period_ns=25.0,
        design_type="large",
        expected_qor=0.40,
        expected_wns=-2.5,
        expected_tns=-60.0,
        expected_utilization=70.0,
        expected_cell_count=20000,
        base_metrics={
            "setup_wns_ns": -2.5, "setup_tns_ns": -60.0,
            "hold_whs_ns": 0.25, "hold_ths_ns": 0.0,
            "utilization": 70.0, "cell_count": 20000,
            "runtime_sec": 800.0, "qor_score": 0.40,
            "overflow_h": 0.06, "overflow_v": 0.05,
            "drc_total_violations": 0, "drc_is_clean": True,
            "lvs_status": "PASS", "lvs_return_code": 0,
            "power_ir_drop_pct": 5.5,
            "clock_skew_ns": 0.35,
            "max_transition_ns": 0.7,
            "max_capacitance_pf": 0.3,
            "implementation_status": "SUCCESS",
            "signoff_status": "PASS",
            "tapeout_ready": True,
            "has_sram_macros": True,
        },
        manifest_path="examples/ibex/gli_manifest.yaml",
        tags=["large", "cpu", "sky130", "sram"],
    ),
    GoldenDesign(
        name="serv",
        top_module="serv_top",
        pdk="sky130A",
        clock_period_ns=15.0,
        design_type="medium",
        expected_qor=0.55,
        expected_wns=-0.8,
        expected_tns=-15.0,
        expected_utilization=50.0,
        expected_cell_count=3000,
        base_metrics={
            "setup_wns_ns": -0.8, "setup_tns_ns": -15.0,
            "hold_whs_ns": 0.08, "hold_ths_ns": 0.0,
            "utilization": 50.0, "cell_count": 3000,
            "runtime_sec": 250.0, "qor_score": 0.55,
            "overflow_h": 0.04, "overflow_v": 0.03,
            "drc_total_violations": 0, "drc_is_clean": True,
            "lvs_status": "PASS", "lvs_return_code": 0,
            "power_ir_drop_pct": 4.5,
            "clock_skew_ns": 0.25,
            "max_transition_ns": 0.55,
            "max_capacitance_pf": 0.22,
            "implementation_status": "SUCCESS",
            "signoff_status": "PASS",
            "tapeout_ready": True,
            "has_sram_macros": False,
        },
        manifest_path="examples/serv/gli_manifest.yaml",
        tags=["medium", "cpu", "sky130", "riscv"],
    ),
    GoldenDesign(
        name="opentitan_ibex",
        top_module="top_earlgrey",
        pdk="sky130A",
        clock_period_ns=30.0,
        design_type="large",
        expected_qor=0.35,
        expected_wns=-3.0,
        expected_tns=-100.0,
        expected_utilization=75.0,
        expected_cell_count=50000,
        base_metrics={
            "setup_wns_ns": -3.0, "setup_tns_ns": -100.0,
            "hold_whs_ns": 0.3, "hold_ths_ns": -5.0,
            "utilization": 75.0, "cell_count": 50000,
            "runtime_sec": 1500.0, "qor_score": 0.35,
            "overflow_h": 0.08, "overflow_v": 0.07,
            "drc_total_violations": 0, "drc_is_clean": True,
            "lvs_status": "PASS", "lvs_return_code": 0,
            "power_ir_drop_pct": 7.0,
            "clock_skew_ns": 0.45,
            "max_transition_ns": 0.85,
            "max_capacitance_pf": 0.35,
            "implementation_status": "SUCCESS",
            "signoff_status": "PASS",
            "tapeout_ready": True,
            "has_sram_macros": True,
        },
        manifest_path="examples/opentitan/gli_manifest.yaml",
        tags=["large", "soc", "sky130", "sram"],
    ),
    GoldenDesign(
        name="tinyml_accel",
        top_module="tinyml_top",
        pdk="sky130A",
        clock_period_ns=12.0,
        design_type="medium",
        expected_qor=0.60,
        expected_wns=-0.3,
        expected_tns=-5.0,
        expected_utilization=55.0,
        expected_cell_count=5000,
        base_metrics={
            "setup_wns_ns": -0.3, "setup_tns_ns": -5.0,
            "hold_whs_ns": 0.05, "hold_ths_ns": 0.0,
            "utilization": 55.0, "cell_count": 5000,
            "runtime_sec": 350.0, "qor_score": 0.60,
            "overflow_h": 0.03, "overflow_v": 0.02,
            "drc_total_violations": 0, "drc_is_clean": True,
            "lvs_status": "PASS", "lvs_return_code": 0,
            "power_ir_drop_pct": 6.0,
            "clock_skew_ns": 0.2,
            "max_transition_ns": 0.45,
            "max_capacitance_pf": 0.18,
            "implementation_status": "SUCCESS",
            "signoff_status": "PASS",
            "tapeout_ready": True,
            "has_sram_macros": True,
        },
        manifest_path="examples/tinyml/gli_manifest.yaml",
        tags=["medium", "ml", "sky130", "sram"],
    ),
    GoldenDesign(
        name="sram_controller",
        top_module="sram_ctrl",
        pdk="sky130A",
        clock_period_ns=8.0,
        design_type="medium",
        expected_qor=0.70,
        expected_wns=0.0,
        expected_tns=0.0,
        expected_utilization=40.0,
        expected_cell_count=2000,
        base_metrics={
            "setup_wns_ns": 0.0, "setup_tns_ns": 0.0,
            "hold_whs_ns": 0.02, "hold_ths_ns": 0.0,
            "utilization": 40.0, "cell_count": 2000,
            "runtime_sec": 120.0, "qor_score": 0.70,
            "overflow_h": 0.02, "overflow_v": 0.01,
            "drc_total_violations": 0, "drc_is_clean": True,
            "lvs_status": "PASS", "lvs_return_code": 0,
            "power_ir_drop_pct": 3.5,
            "clock_skew_ns": 0.12,
            "max_transition_ns": 0.35,
            "max_capacitance_pf": 0.12,
            "implementation_status": "SUCCESS",
            "signoff_status": "PASS",
            "tapeout_ready": True,
            "has_sram_macros": True,
        },
        manifest_path="examples/sram_ctrl/gli_manifest.yaml",
        tags=["medium", "memory", "sky130", "sram"],
    ),
    GoldenDesign(
        name="aes_cipher",
        top_module="aes_cipher_top",
        pdk="sky130A",
        clock_period_ns=10.0,
        design_type="medium",
        expected_qor=0.72,
        expected_wns=-0.05,
        expected_tns=-1.0,
        expected_utilization=45.0,
        expected_cell_count=3500,
        base_metrics={
            "setup_wns_ns": -0.05, "setup_tns_ns": -1.0,
            "hold_whs_ns": 0.04, "hold_ths_ns": 0.0,
            "utilization": 45.0, "cell_count": 3500,
            "runtime_sec": 200.0, "qor_score": 0.72,
            "overflow_h": 0.02, "overflow_v": 0.02,
            "drc_total_violations": 0, "drc_is_clean": True,
            "lvs_status": "PASS", "lvs_return_code": 0,
            "power_ir_drop_pct": 4.0,
            "clock_skew_ns": 0.15,
            "max_transition_ns": 0.4,
            "max_capacitance_pf": 0.15,
            "implementation_status": "SUCCESS",
            "signoff_status": "PASS",
            "tapeout_ready": True,
            "has_sram_macros": False,
        },
        manifest_path="examples/aes/gli_manifest.yaml",
        tags=["medium", "crypto", "sky130"],
    ),
]


class SyntheticDatasetManager:
    def __init__(self):
        self._designs = {d.name: d for d in GOLDEN_DESIGNS}

    def list_designs(self) -> list[GoldenDesign]:
        return list(self._designs.values())

    def get_design(self, name: str) -> Optional[GoldenDesign]:
        return self._designs.get(name)

    def get_by_tag(self, tag: str) -> list[GoldenDesign]:
        return [d for d in GOLDEN_DESIGNS if tag in d.tags]

    def get_by_type(self, design_type: str) -> list[GoldenDesign]:
        return [d for d in GOLDEN_DESIGNS if d.design_type == design_type]

    @staticmethod
    def generate_catalog() -> dict:
        return {
            "version": "1.0.0",
            "generated_by": "SyntheticDatasetManager",
            "designs": [
                {
                    "name": d.name,
                    "top_module": d.top_module,
                    "pdk": d.pdk,
                    "clock_period_ns": d.clock_period_ns,
                    "design_type": d.design_type,
                    "expected_qor": d.expected_qor,
                    "fingerprint": d.fingerprint,
                    "tags": d.tags,
                    "manifest": d.manifest_path,
                }
                for d in GOLDEN_DESIGNS
            ],
        }


golden_design_catalog = SyntheticDatasetManager.generate_catalog()
