from enum import Enum


class ExecutionStage(Enum):

    INITIALIZING = "INITIALIZING"

    HIERARCHICAL_PARTITIONING = "HIERARCHICAL_PARTITIONING"

    BLOCK_SYNTHESIS = "BLOCK_SYNTHESIS"

    SYNTHESIS = "SYNTHESIS"

    CLOCK_GATING = "CLOCK_GATING"

    SCAN_INSERTION = "SCAN_INSERTION"

    FORMAL_VERIFICATION = "FORMAL_VERIFICATION"

    FLOORPLANNING = "FLOORPLANNING"

    TOP_FLOORPLANNING = "TOP_FLOORPLANNING"

    PLACEMENT = "PLACEMENT"

    CTS = "CTS"

    ROUTING = "ROUTING"

    PRO = "PRO"

    ANTENNA_CHECK = "ANTENNA_CHECK"

    FILL = "FILL"

    DECAP = "DECAP"

    POWER = "POWER"

    EM_CHECK = "EM_CHECK"

    DENSITY_CHECK = "DENSITY_CHECK"

    YIELD = "YIELD"

    DRC = "DRC"

    LVS = "LVS"

    ATPG = "ATPG"

    TIMING_ANALYSIS = "TIMING_ANALYSIS"

    SI_ANALYSIS = "SI_ANALYSIS"

    SIGN_OFF = "SIGN_OFF"

    D2D_INTERFACE_CHECK = "D2D_INTERFACE_CHECK"

    QOR_EXTRACTION = "QOR_EXTRACTION"

    PACKAGING = "PACKAGING"
