// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Tracing implementation internals
#include "verilated_vcd_c.h"
#include "Vmac_top__Syms.h"


void Vmac_top___024root__trace_chg_0_sub_0(Vmac_top___024root* vlSelf, VerilatedVcd::Buffer* bufp);

void Vmac_top___024root__trace_chg_0(void* voidSelf, VerilatedVcd::Buffer* bufp) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vmac_top___024root__trace_chg_0\n"); );
    // Init
    Vmac_top___024root* const __restrict vlSelf VL_ATTR_UNUSED = static_cast<Vmac_top___024root*>(voidSelf);
    Vmac_top__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    if (VL_UNLIKELY(!vlSymsp->__Vm_activity)) return;
    // Body
    Vmac_top___024root__trace_chg_0_sub_0((&vlSymsp->TOP), bufp);
}

void Vmac_top___024root__trace_chg_0_sub_0(Vmac_top___024root* vlSelf, VerilatedVcd::Buffer* bufp) {
    if (false && vlSelf) {}  // Prevent unused
    Vmac_top__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vmac_top___024root__trace_chg_0_sub_0\n"); );
    // Init
    uint32_t* const oldp VL_ATTR_UNUSED = bufp->oldp(vlSymsp->__Vm_baseCode + 1);
    // Body
    if (VL_UNLIKELY(vlSelf->__Vm_traceActivity[0U])) {
        bufp->chgIData(oldp+0,(vlSelf->mac_top__DOT__col_in[0]),32);
        bufp->chgIData(oldp+1,(vlSelf->mac_top__DOT__col_in[1]),32);
        bufp->chgIData(oldp+2,(vlSelf->mac_top__DOT__col_in[2]),32);
        bufp->chgIData(oldp+3,(vlSelf->mac_top__DOT__col_in[3]),32);
        bufp->chgIData(oldp+4,(vlSelf->mac_top__DOT__col_in
                               [0U]),32);
        bufp->chgIData(oldp+5,(vlSelf->mac_top__DOT__col_in
                               [1U]),32);
        bufp->chgIData(oldp+6,(vlSelf->mac_top__DOT__col_in
                               [2U]),32);
        bufp->chgIData(oldp+7,(vlSelf->mac_top__DOT__col_in
                               [3U]),32);
        bufp->chgIData(oldp+8,(vlSelf->mac_top__DOT__u_array__DOT__col_in[0]),32);
        bufp->chgIData(oldp+9,(vlSelf->mac_top__DOT__u_array__DOT__col_in[1]),32);
        bufp->chgIData(oldp+10,(vlSelf->mac_top__DOT__u_array__DOT__col_in[2]),32);
        bufp->chgIData(oldp+11,(vlSelf->mac_top__DOT__u_array__DOT__col_in[3]),32);
    }
    if (VL_UNLIKELY(vlSelf->__Vm_traceActivity[1U])) {
        bufp->chgBit(oldp+12,(vlSelf->mac_top__DOT__start));
        bufp->chgCData(oldp+13,(vlSelf->mac_top__DOT__reg_m),8);
        bufp->chgCData(oldp+14,(vlSelf->mac_top__DOT__reg_k),8);
        bufp->chgCData(oldp+15,(vlSelf->mac_top__DOT__reg_n),8);
        bufp->chgIData(oldp+16,(vlSelf->mac_top__DOT__wgt_addr),32);
        bufp->chgIData(oldp+17,(vlSelf->mac_top__DOT__act_addr),32);
        bufp->chgIData(oldp+18,(vlSelf->mac_top__DOT__res_addr),32);
        bufp->chgCData(oldp+19,(vlSelf->mac_top__DOT__wgt_buf
                                [0U][0U]),8);
        bufp->chgCData(oldp+20,(vlSelf->mac_top__DOT__wgt_buf
                                [0U][1U]),8);
        bufp->chgCData(oldp+21,(vlSelf->mac_top__DOT__wgt_buf
                                [0U][2U]),8);
        bufp->chgCData(oldp+22,(vlSelf->mac_top__DOT__wgt_buf
                                [0U][3U]),8);
        bufp->chgCData(oldp+23,(vlSelf->mac_top__DOT__wgt_buf
                                [1U][0U]),8);
        bufp->chgCData(oldp+24,(vlSelf->mac_top__DOT__wgt_buf
                                [1U][1U]),8);
        bufp->chgCData(oldp+25,(vlSelf->mac_top__DOT__wgt_buf
                                [1U][2U]),8);
        bufp->chgCData(oldp+26,(vlSelf->mac_top__DOT__wgt_buf
                                [1U][3U]),8);
        bufp->chgCData(oldp+27,(vlSelf->mac_top__DOT__wgt_buf
                                [2U][0U]),8);
        bufp->chgCData(oldp+28,(vlSelf->mac_top__DOT__wgt_buf
                                [2U][1U]),8);
        bufp->chgCData(oldp+29,(vlSelf->mac_top__DOT__wgt_buf
                                [2U][2U]),8);
        bufp->chgCData(oldp+30,(vlSelf->mac_top__DOT__wgt_buf
                                [2U][3U]),8);
        bufp->chgCData(oldp+31,(vlSelf->mac_top__DOT__wgt_buf
                                [3U][0U]),8);
        bufp->chgCData(oldp+32,(vlSelf->mac_top__DOT__wgt_buf
                                [3U][1U]),8);
        bufp->chgCData(oldp+33,(vlSelf->mac_top__DOT__wgt_buf
                                [3U][2U]),8);
        bufp->chgCData(oldp+34,(vlSelf->mac_top__DOT__wgt_buf
                                [3U][3U]),8);
        bufp->chgCData(oldp+35,(vlSelf->mac_top__DOT__weight_in
                                [0U][0U]),8);
        bufp->chgCData(oldp+36,(vlSelf->mac_top__DOT__weight_in
                                [0U][1U]),8);
        bufp->chgCData(oldp+37,(vlSelf->mac_top__DOT__weight_in
                                [0U][2U]),8);
        bufp->chgCData(oldp+38,(vlSelf->mac_top__DOT__weight_in
                                [0U][3U]),8);
        bufp->chgCData(oldp+39,(vlSelf->mac_top__DOT__weight_in
                                [1U][0U]),8);
        bufp->chgCData(oldp+40,(vlSelf->mac_top__DOT__weight_in
                                [1U][1U]),8);
        bufp->chgCData(oldp+41,(vlSelf->mac_top__DOT__weight_in
                                [1U][2U]),8);
        bufp->chgCData(oldp+42,(vlSelf->mac_top__DOT__weight_in
                                [1U][3U]),8);
        bufp->chgCData(oldp+43,(vlSelf->mac_top__DOT__weight_in
                                [2U][0U]),8);
        bufp->chgCData(oldp+44,(vlSelf->mac_top__DOT__weight_in
                                [2U][1U]),8);
        bufp->chgCData(oldp+45,(vlSelf->mac_top__DOT__weight_in
                                [2U][2U]),8);
        bufp->chgCData(oldp+46,(vlSelf->mac_top__DOT__weight_in
                                [2U][3U]),8);
        bufp->chgCData(oldp+47,(vlSelf->mac_top__DOT__weight_in
                                [3U][0U]),8);
        bufp->chgCData(oldp+48,(vlSelf->mac_top__DOT__weight_in
                                [3U][1U]),8);
        bufp->chgCData(oldp+49,(vlSelf->mac_top__DOT__weight_in
                                [3U][2U]),8);
        bufp->chgCData(oldp+50,(vlSelf->mac_top__DOT__weight_in
                                [3U][3U]),8);
        bufp->chgCData(oldp+51,(vlSelf->mac_top__DOT__act_buf[0]),8);
        bufp->chgCData(oldp+52,(vlSelf->mac_top__DOT__act_buf[1]),8);
        bufp->chgCData(oldp+53,(vlSelf->mac_top__DOT__act_buf[2]),8);
        bufp->chgCData(oldp+54,(vlSelf->mac_top__DOT__act_buf[3]),8);
        bufp->chgBit(oldp+55,(vlSelf->mac_top__DOT__load_wgt));
        bufp->chgCData(oldp+56,(vlSelf->mac_top__DOT__row_in[0]),8);
        bufp->chgCData(oldp+57,(vlSelf->mac_top__DOT__row_in[1]),8);
        bufp->chgCData(oldp+58,(vlSelf->mac_top__DOT__row_in[2]),8);
        bufp->chgCData(oldp+59,(vlSelf->mac_top__DOT__row_in[3]),8);
        bufp->chgIData(oldp+60,(vlSelf->mac_top__DOT__col_out[0]),32);
        bufp->chgIData(oldp+61,(vlSelf->mac_top__DOT__col_out[1]),32);
        bufp->chgIData(oldp+62,(vlSelf->mac_top__DOT__col_out[2]),32);
        bufp->chgIData(oldp+63,(vlSelf->mac_top__DOT__col_out[3]),32);
        bufp->chgCData(oldp+64,(vlSelf->mac_top__DOT__state),4);
        bufp->chgCData(oldp+65,(vlSelf->mac_top__DOT__wgt_cnt),2);
        bufp->chgCData(oldp+66,(vlSelf->mac_top__DOT__res_cnt),2);
        bufp->chgCData(oldp+67,(vlSelf->mac_top__DOT__row_cnt),8);
        bufp->chgCData(oldp+68,(vlSelf->mac_top__DOT__feed_cnt),4);
        bufp->chgCData(oldp+69,(vlSelf->mac_top__DOT__drain_cnt),4);
        bufp->chgBit(oldp+70,(vlSelf->mac_top__DOT__wgt_done_r));
        bufp->chgBit(oldp+71,(vlSelf->mac_top__DOT__res_done_r));
        bufp->chgIData(oldp+72,(vlSelf->mac_top__DOT__result_hold[0]),32);
        bufp->chgIData(oldp+73,(vlSelf->mac_top__DOT__result_hold[1]),32);
        bufp->chgIData(oldp+74,(vlSelf->mac_top__DOT__result_hold[2]),32);
        bufp->chgIData(oldp+75,(vlSelf->mac_top__DOT__result_hold[3]),32);
        bufp->chgBit(oldp+76,(vlSelf->mac_top__DOT__m_req_c));
        bufp->chgIData(oldp+77,(vlSelf->mac_top__DOT__m_addr_c),32);
        bufp->chgBit(oldp+78,(vlSelf->mac_top__DOT__m_we_c));
        bufp->chgIData(oldp+79,(vlSelf->mac_top__DOT__m_wdata_c),32);
        bufp->chgCData(oldp+80,(vlSelf->mac_top__DOT__row_in
                                [0U]),8);
        bufp->chgCData(oldp+81,(vlSelf->mac_top__DOT__row_in
                                [1U]),8);
        bufp->chgCData(oldp+82,(vlSelf->mac_top__DOT__row_in
                                [2U]),8);
        bufp->chgCData(oldp+83,(vlSelf->mac_top__DOT__row_in
                                [3U]),8);
        bufp->chgCData(oldp+84,(vlSelf->mac_top__DOT__weight_in
                                [0U][0U]),8);
        bufp->chgCData(oldp+85,(vlSelf->mac_top__DOT__weight_in
                                [0U][1U]),8);
        bufp->chgCData(oldp+86,(vlSelf->mac_top__DOT__weight_in
                                [0U][2U]),8);
        bufp->chgCData(oldp+87,(vlSelf->mac_top__DOT__weight_in
                                [0U][3U]),8);
        bufp->chgCData(oldp+88,(vlSelf->mac_top__DOT__weight_in
                                [1U][0U]),8);
        bufp->chgCData(oldp+89,(vlSelf->mac_top__DOT__weight_in
                                [1U][1U]),8);
        bufp->chgCData(oldp+90,(vlSelf->mac_top__DOT__weight_in
                                [1U][2U]),8);
        bufp->chgCData(oldp+91,(vlSelf->mac_top__DOT__weight_in
                                [1U][3U]),8);
        bufp->chgCData(oldp+92,(vlSelf->mac_top__DOT__weight_in
                                [2U][0U]),8);
        bufp->chgCData(oldp+93,(vlSelf->mac_top__DOT__weight_in
                                [2U][1U]),8);
        bufp->chgCData(oldp+94,(vlSelf->mac_top__DOT__weight_in
                                [2U][2U]),8);
        bufp->chgCData(oldp+95,(vlSelf->mac_top__DOT__weight_in
                                [2U][3U]),8);
        bufp->chgCData(oldp+96,(vlSelf->mac_top__DOT__weight_in
                                [3U][0U]),8);
        bufp->chgCData(oldp+97,(vlSelf->mac_top__DOT__weight_in
                                [3U][1U]),8);
        bufp->chgCData(oldp+98,(vlSelf->mac_top__DOT__weight_in
                                [3U][2U]),8);
        bufp->chgCData(oldp+99,(vlSelf->mac_top__DOT__weight_in
                                [3U][3U]),8);
        bufp->chgIData(oldp+100,(vlSelf->mac_top__DOT__u_array__DOT__col_out
                                 [0U]),32);
        bufp->chgIData(oldp+101,(vlSelf->mac_top__DOT__u_array__DOT__col_out
                                 [1U]),32);
        bufp->chgIData(oldp+102,(vlSelf->mac_top__DOT__u_array__DOT__col_out
                                 [2U]),32);
        bufp->chgIData(oldp+103,(vlSelf->mac_top__DOT__u_array__DOT__col_out
                                 [3U]),32);
        bufp->chgCData(oldp+104,(vlSelf->mac_top__DOT__u_array__DOT__row_in[0]),8);
        bufp->chgCData(oldp+105,(vlSelf->mac_top__DOT__u_array__DOT__row_in[1]),8);
        bufp->chgCData(oldp+106,(vlSelf->mac_top__DOT__u_array__DOT__row_in[2]),8);
        bufp->chgCData(oldp+107,(vlSelf->mac_top__DOT__u_array__DOT__row_in[3]),8);
        bufp->chgCData(oldp+108,(vlSelf->mac_top__DOT__u_array__DOT__weight_in
                                 [0U][0U]),8);
        bufp->chgCData(oldp+109,(vlSelf->mac_top__DOT__u_array__DOT__weight_in
                                 [0U][1U]),8);
        bufp->chgCData(oldp+110,(vlSelf->mac_top__DOT__u_array__DOT__weight_in
                                 [0U][2U]),8);
        bufp->chgCData(oldp+111,(vlSelf->mac_top__DOT__u_array__DOT__weight_in
                                 [0U][3U]),8);
        bufp->chgCData(oldp+112,(vlSelf->mac_top__DOT__u_array__DOT__weight_in
                                 [1U][0U]),8);
        bufp->chgCData(oldp+113,(vlSelf->mac_top__DOT__u_array__DOT__weight_in
                                 [1U][1U]),8);
        bufp->chgCData(oldp+114,(vlSelf->mac_top__DOT__u_array__DOT__weight_in
                                 [1U][2U]),8);
        bufp->chgCData(oldp+115,(vlSelf->mac_top__DOT__u_array__DOT__weight_in
                                 [1U][3U]),8);
        bufp->chgCData(oldp+116,(vlSelf->mac_top__DOT__u_array__DOT__weight_in
                                 [2U][0U]),8);
        bufp->chgCData(oldp+117,(vlSelf->mac_top__DOT__u_array__DOT__weight_in
                                 [2U][1U]),8);
        bufp->chgCData(oldp+118,(vlSelf->mac_top__DOT__u_array__DOT__weight_in
                                 [2U][2U]),8);
        bufp->chgCData(oldp+119,(vlSelf->mac_top__DOT__u_array__DOT__weight_in
                                 [2U][3U]),8);
        bufp->chgCData(oldp+120,(vlSelf->mac_top__DOT__u_array__DOT__weight_in
                                 [3U][0U]),8);
        bufp->chgCData(oldp+121,(vlSelf->mac_top__DOT__u_array__DOT__weight_in
                                 [3U][1U]),8);
        bufp->chgCData(oldp+122,(vlSelf->mac_top__DOT__u_array__DOT__weight_in
                                 [3U][2U]),8);
        bufp->chgCData(oldp+123,(vlSelf->mac_top__DOT__u_array__DOT__weight_in
                                 [3U][3U]),8);
        bufp->chgIData(oldp+124,(vlSelf->mac_top__DOT__u_array__DOT__col_out[0]),32);
        bufp->chgIData(oldp+125,(vlSelf->mac_top__DOT__u_array__DOT__col_out[1]),32);
        bufp->chgIData(oldp+126,(vlSelf->mac_top__DOT__u_array__DOT__col_out[2]),32);
        bufp->chgIData(oldp+127,(vlSelf->mac_top__DOT__u_array__DOT__col_out[3]),32);
        bufp->chgCData(oldp+128,(vlSelf->mac_top__DOT__u_array__DOT__h_wire
                                 [0U][0U]),8);
        bufp->chgCData(oldp+129,(vlSelf->mac_top__DOT__u_array__DOT__h_wire
                                 [0U][1U]),8);
        bufp->chgCData(oldp+130,(vlSelf->mac_top__DOT__u_array__DOT__h_wire
                                 [0U][2U]),8);
        bufp->chgCData(oldp+131,(vlSelf->mac_top__DOT__u_array__DOT__h_wire
                                 [0U][3U]),8);
        bufp->chgCData(oldp+132,(vlSelf->mac_top__DOT__u_array__DOT__h_wire
                                 [0U][4U]),8);
        bufp->chgCData(oldp+133,(vlSelf->mac_top__DOT__u_array__DOT__h_wire
                                 [1U][0U]),8);
        bufp->chgCData(oldp+134,(vlSelf->mac_top__DOT__u_array__DOT__h_wire
                                 [1U][1U]),8);
        bufp->chgCData(oldp+135,(vlSelf->mac_top__DOT__u_array__DOT__h_wire
                                 [1U][2U]),8);
        bufp->chgCData(oldp+136,(vlSelf->mac_top__DOT__u_array__DOT__h_wire
                                 [1U][3U]),8);
        bufp->chgCData(oldp+137,(vlSelf->mac_top__DOT__u_array__DOT__h_wire
                                 [1U][4U]),8);
        bufp->chgCData(oldp+138,(vlSelf->mac_top__DOT__u_array__DOT__h_wire
                                 [2U][0U]),8);
        bufp->chgCData(oldp+139,(vlSelf->mac_top__DOT__u_array__DOT__h_wire
                                 [2U][1U]),8);
        bufp->chgCData(oldp+140,(vlSelf->mac_top__DOT__u_array__DOT__h_wire
                                 [2U][2U]),8);
        bufp->chgCData(oldp+141,(vlSelf->mac_top__DOT__u_array__DOT__h_wire
                                 [2U][3U]),8);
        bufp->chgCData(oldp+142,(vlSelf->mac_top__DOT__u_array__DOT__h_wire
                                 [2U][4U]),8);
        bufp->chgCData(oldp+143,(vlSelf->mac_top__DOT__u_array__DOT__h_wire
                                 [3U][0U]),8);
        bufp->chgCData(oldp+144,(vlSelf->mac_top__DOT__u_array__DOT__h_wire
                                 [3U][1U]),8);
        bufp->chgCData(oldp+145,(vlSelf->mac_top__DOT__u_array__DOT__h_wire
                                 [3U][2U]),8);
        bufp->chgCData(oldp+146,(vlSelf->mac_top__DOT__u_array__DOT__h_wire
                                 [3U][3U]),8);
        bufp->chgCData(oldp+147,(vlSelf->mac_top__DOT__u_array__DOT__h_wire
                                 [3U][4U]),8);
        bufp->chgIData(oldp+148,(vlSelf->mac_top__DOT__u_array__DOT__v_wire
                                 [0U][0U]),32);
        bufp->chgIData(oldp+149,(vlSelf->mac_top__DOT__u_array__DOT__v_wire
                                 [0U][1U]),32);
        bufp->chgIData(oldp+150,(vlSelf->mac_top__DOT__u_array__DOT__v_wire
                                 [0U][2U]),32);
        bufp->chgIData(oldp+151,(vlSelf->mac_top__DOT__u_array__DOT__v_wire
                                 [0U][3U]),32);
        bufp->chgIData(oldp+152,(vlSelf->mac_top__DOT__u_array__DOT__v_wire
                                 [1U][0U]),32);
        bufp->chgIData(oldp+153,(vlSelf->mac_top__DOT__u_array__DOT__v_wire
                                 [1U][1U]),32);
        bufp->chgIData(oldp+154,(vlSelf->mac_top__DOT__u_array__DOT__v_wire
                                 [1U][2U]),32);
        bufp->chgIData(oldp+155,(vlSelf->mac_top__DOT__u_array__DOT__v_wire
                                 [1U][3U]),32);
        bufp->chgIData(oldp+156,(vlSelf->mac_top__DOT__u_array__DOT__v_wire
                                 [2U][0U]),32);
        bufp->chgIData(oldp+157,(vlSelf->mac_top__DOT__u_array__DOT__v_wire
                                 [2U][1U]),32);
        bufp->chgIData(oldp+158,(vlSelf->mac_top__DOT__u_array__DOT__v_wire
                                 [2U][2U]),32);
        bufp->chgIData(oldp+159,(vlSelf->mac_top__DOT__u_array__DOT__v_wire
                                 [2U][3U]),32);
        bufp->chgIData(oldp+160,(vlSelf->mac_top__DOT__u_array__DOT__v_wire
                                 [3U][0U]),32);
        bufp->chgIData(oldp+161,(vlSelf->mac_top__DOT__u_array__DOT__v_wire
                                 [3U][1U]),32);
        bufp->chgIData(oldp+162,(vlSelf->mac_top__DOT__u_array__DOT__v_wire
                                 [3U][2U]),32);
        bufp->chgIData(oldp+163,(vlSelf->mac_top__DOT__u_array__DOT__v_wire
                                 [3U][3U]),32);
        bufp->chgIData(oldp+164,(vlSelf->mac_top__DOT__u_array__DOT__v_wire
                                 [4U][0U]),32);
        bufp->chgIData(oldp+165,(vlSelf->mac_top__DOT__u_array__DOT__v_wire
                                 [4U][1U]),32);
        bufp->chgIData(oldp+166,(vlSelf->mac_top__DOT__u_array__DOT__v_wire
                                 [4U][2U]),32);
        bufp->chgIData(oldp+167,(vlSelf->mac_top__DOT__u_array__DOT__v_wire
                                 [4U][3U]),32);
        bufp->chgCData(oldp+168,(vlSelf->mac_top__DOT__u_array__DOT__h_wire
                                 [0U][0U]),8);
        bufp->chgCData(oldp+169,(vlSelf->mac_top__DOT__u_array__DOT__weight_in
                                 [0U][0U]),8);
        bufp->chgIData(oldp+170,(vlSelf->mac_top__DOT__u_array__DOT__v_wire
                                 [0U][0U]),32);
        bufp->chgCData(oldp+171,(vlSelf->mac_top__DOT__u_array__DOT____Vcellout__gen_rows__BRA__0__KET____DOT__gen_cols__BRA__0__KET____DOT__inst_pe__a_out),8);
        bufp->chgIData(oldp+172,(vlSelf->mac_top__DOT__u_array__DOT____Vcellout__gen_rows__BRA__0__KET____DOT__gen_cols__BRA__0__KET____DOT__inst_pe__acc_out),32);
        bufp->chgCData(oldp+173,(vlSelf->mac_top__DOT__u_array__DOT__gen_rows__BRA__0__KET____DOT__gen_cols__BRA__0__KET____DOT__inst_pe__DOT__a_reg),8);
        bufp->chgCData(oldp+174,(vlSelf->mac_top__DOT__u_array__DOT__gen_rows__BRA__0__KET____DOT__gen_cols__BRA__0__KET____DOT__inst_pe__DOT__w_reg),8);
        bufp->chgSData(oldp+175,(vlSelf->mac_top__DOT__u_array__DOT__gen_rows__BRA__0__KET____DOT__gen_cols__BRA__0__KET____DOT__inst_pe__DOT__mul_reg),16);
        bufp->chgCData(oldp+176,(vlSelf->mac_top__DOT__u_array__DOT__h_wire
                                 [0U][1U]),8);
        bufp->chgCData(oldp+177,(vlSelf->mac_top__DOT__u_array__DOT__weight_in
                                 [0U][1U]),8);
        bufp->chgIData(oldp+178,(vlSelf->mac_top__DOT__u_array__DOT__v_wire
                                 [0U][1U]),32);
        bufp->chgCData(oldp+179,(vlSelf->mac_top__DOT__u_array__DOT____Vcellout__gen_rows__BRA__0__KET____DOT__gen_cols__BRA__1__KET____DOT__inst_pe__a_out),8);
        bufp->chgIData(oldp+180,(vlSelf->mac_top__DOT__u_array__DOT____Vcellout__gen_rows__BRA__0__KET____DOT__gen_cols__BRA__1__KET____DOT__inst_pe__acc_out),32);
        bufp->chgCData(oldp+181,(vlSelf->mac_top__DOT__u_array__DOT__gen_rows__BRA__0__KET____DOT__gen_cols__BRA__1__KET____DOT__inst_pe__DOT__a_reg),8);
        bufp->chgCData(oldp+182,(vlSelf->mac_top__DOT__u_array__DOT__gen_rows__BRA__0__KET____DOT__gen_cols__BRA__1__KET____DOT__inst_pe__DOT__w_reg),8);
        bufp->chgSData(oldp+183,(vlSelf->mac_top__DOT__u_array__DOT__gen_rows__BRA__0__KET____DOT__gen_cols__BRA__1__KET____DOT__inst_pe__DOT__mul_reg),16);
        bufp->chgCData(oldp+184,(vlSelf->mac_top__DOT__u_array__DOT__h_wire
                                 [0U][2U]),8);
        bufp->chgCData(oldp+185,(vlSelf->mac_top__DOT__u_array__DOT__weight_in
                                 [0U][2U]),8);
        bufp->chgIData(oldp+186,(vlSelf->mac_top__DOT__u_array__DOT__v_wire
                                 [0U][2U]),32);
        bufp->chgCData(oldp+187,(vlSelf->mac_top__DOT__u_array__DOT____Vcellout__gen_rows__BRA__0__KET____DOT__gen_cols__BRA__2__KET____DOT__inst_pe__a_out),8);
        bufp->chgIData(oldp+188,(vlSelf->mac_top__DOT__u_array__DOT____Vcellout__gen_rows__BRA__0__KET____DOT__gen_cols__BRA__2__KET____DOT__inst_pe__acc_out),32);
        bufp->chgCData(oldp+189,(vlSelf->mac_top__DOT__u_array__DOT__gen_rows__BRA__0__KET____DOT__gen_cols__BRA__2__KET____DOT__inst_pe__DOT__a_reg),8);
        bufp->chgCData(oldp+190,(vlSelf->mac_top__DOT__u_array__DOT__gen_rows__BRA__0__KET____DOT__gen_cols__BRA__2__KET____DOT__inst_pe__DOT__w_reg),8);
        bufp->chgSData(oldp+191,(vlSelf->mac_top__DOT__u_array__DOT__gen_rows__BRA__0__KET____DOT__gen_cols__BRA__2__KET____DOT__inst_pe__DOT__mul_reg),16);
        bufp->chgCData(oldp+192,(vlSelf->mac_top__DOT__u_array__DOT__h_wire
                                 [0U][3U]),8);
        bufp->chgCData(oldp+193,(vlSelf->mac_top__DOT__u_array__DOT__weight_in
                                 [0U][3U]),8);
        bufp->chgIData(oldp+194,(vlSelf->mac_top__DOT__u_array__DOT__v_wire
                                 [0U][3U]),32);
        bufp->chgCData(oldp+195,(vlSelf->mac_top__DOT__u_array__DOT____Vcellout__gen_rows__BRA__0__KET____DOT__gen_cols__BRA__3__KET____DOT__inst_pe__a_out),8);
        bufp->chgIData(oldp+196,(vlSelf->mac_top__DOT__u_array__DOT____Vcellout__gen_rows__BRA__0__KET____DOT__gen_cols__BRA__3__KET____DOT__inst_pe__acc_out),32);
        bufp->chgCData(oldp+197,(vlSelf->mac_top__DOT__u_array__DOT__gen_rows__BRA__0__KET____DOT__gen_cols__BRA__3__KET____DOT__inst_pe__DOT__a_reg),8);
        bufp->chgCData(oldp+198,(vlSelf->mac_top__DOT__u_array__DOT__gen_rows__BRA__0__KET____DOT__gen_cols__BRA__3__KET____DOT__inst_pe__DOT__w_reg),8);
        bufp->chgSData(oldp+199,(vlSelf->mac_top__DOT__u_array__DOT__gen_rows__BRA__0__KET____DOT__gen_cols__BRA__3__KET____DOT__inst_pe__DOT__mul_reg),16);
        bufp->chgCData(oldp+200,(vlSelf->mac_top__DOT__u_array__DOT__h_wire
                                 [1U][0U]),8);
        bufp->chgCData(oldp+201,(vlSelf->mac_top__DOT__u_array__DOT__weight_in
                                 [1U][0U]),8);
        bufp->chgIData(oldp+202,(vlSelf->mac_top__DOT__u_array__DOT__v_wire
                                 [1U][0U]),32);
        bufp->chgCData(oldp+203,(vlSelf->mac_top__DOT__u_array__DOT____Vcellout__gen_rows__BRA__1__KET____DOT__gen_cols__BRA__0__KET____DOT__inst_pe__a_out),8);
        bufp->chgIData(oldp+204,(vlSelf->mac_top__DOT__u_array__DOT____Vcellout__gen_rows__BRA__1__KET____DOT__gen_cols__BRA__0__KET____DOT__inst_pe__acc_out),32);
        bufp->chgCData(oldp+205,(vlSelf->mac_top__DOT__u_array__DOT__gen_rows__BRA__1__KET____DOT__gen_cols__BRA__0__KET____DOT__inst_pe__DOT__a_reg),8);
        bufp->chgCData(oldp+206,(vlSelf->mac_top__DOT__u_array__DOT__gen_rows__BRA__1__KET____DOT__gen_cols__BRA__0__KET____DOT__inst_pe__DOT__w_reg),8);
        bufp->chgSData(oldp+207,(vlSelf->mac_top__DOT__u_array__DOT__gen_rows__BRA__1__KET____DOT__gen_cols__BRA__0__KET____DOT__inst_pe__DOT__mul_reg),16);
        bufp->chgCData(oldp+208,(vlSelf->mac_top__DOT__u_array__DOT__h_wire
                                 [1U][1U]),8);
        bufp->chgCData(oldp+209,(vlSelf->mac_top__DOT__u_array__DOT__weight_in
                                 [1U][1U]),8);
        bufp->chgIData(oldp+210,(vlSelf->mac_top__DOT__u_array__DOT__v_wire
                                 [1U][1U]),32);
        bufp->chgCData(oldp+211,(vlSelf->mac_top__DOT__u_array__DOT____Vcellout__gen_rows__BRA__1__KET____DOT__gen_cols__BRA__1__KET____DOT__inst_pe__a_out),8);
        bufp->chgIData(oldp+212,(vlSelf->mac_top__DOT__u_array__DOT____Vcellout__gen_rows__BRA__1__KET____DOT__gen_cols__BRA__1__KET____DOT__inst_pe__acc_out),32);
        bufp->chgCData(oldp+213,(vlSelf->mac_top__DOT__u_array__DOT__gen_rows__BRA__1__KET____DOT__gen_cols__BRA__1__KET____DOT__inst_pe__DOT__a_reg),8);
        bufp->chgCData(oldp+214,(vlSelf->mac_top__DOT__u_array__DOT__gen_rows__BRA__1__KET____DOT__gen_cols__BRA__1__KET____DOT__inst_pe__DOT__w_reg),8);
        bufp->chgSData(oldp+215,(vlSelf->mac_top__DOT__u_array__DOT__gen_rows__BRA__1__KET____DOT__gen_cols__BRA__1__KET____DOT__inst_pe__DOT__mul_reg),16);
        bufp->chgCData(oldp+216,(vlSelf->mac_top__DOT__u_array__DOT__h_wire
                                 [1U][2U]),8);
        bufp->chgCData(oldp+217,(vlSelf->mac_top__DOT__u_array__DOT__weight_in
                                 [1U][2U]),8);
        bufp->chgIData(oldp+218,(vlSelf->mac_top__DOT__u_array__DOT__v_wire
                                 [1U][2U]),32);
        bufp->chgCData(oldp+219,(vlSelf->mac_top__DOT__u_array__DOT____Vcellout__gen_rows__BRA__1__KET____DOT__gen_cols__BRA__2__KET____DOT__inst_pe__a_out),8);
        bufp->chgIData(oldp+220,(vlSelf->mac_top__DOT__u_array__DOT____Vcellout__gen_rows__BRA__1__KET____DOT__gen_cols__BRA__2__KET____DOT__inst_pe__acc_out),32);
        bufp->chgCData(oldp+221,(vlSelf->mac_top__DOT__u_array__DOT__gen_rows__BRA__1__KET____DOT__gen_cols__BRA__2__KET____DOT__inst_pe__DOT__a_reg),8);
        bufp->chgCData(oldp+222,(vlSelf->mac_top__DOT__u_array__DOT__gen_rows__BRA__1__KET____DOT__gen_cols__BRA__2__KET____DOT__inst_pe__DOT__w_reg),8);
        bufp->chgSData(oldp+223,(vlSelf->mac_top__DOT__u_array__DOT__gen_rows__BRA__1__KET____DOT__gen_cols__BRA__2__KET____DOT__inst_pe__DOT__mul_reg),16);
        bufp->chgCData(oldp+224,(vlSelf->mac_top__DOT__u_array__DOT__h_wire
                                 [1U][3U]),8);
        bufp->chgCData(oldp+225,(vlSelf->mac_top__DOT__u_array__DOT__weight_in
                                 [1U][3U]),8);
        bufp->chgIData(oldp+226,(vlSelf->mac_top__DOT__u_array__DOT__v_wire
                                 [1U][3U]),32);
        bufp->chgCData(oldp+227,(vlSelf->mac_top__DOT__u_array__DOT____Vcellout__gen_rows__BRA__1__KET____DOT__gen_cols__BRA__3__KET____DOT__inst_pe__a_out),8);
        bufp->chgIData(oldp+228,(vlSelf->mac_top__DOT__u_array__DOT____Vcellout__gen_rows__BRA__1__KET____DOT__gen_cols__BRA__3__KET____DOT__inst_pe__acc_out),32);
        bufp->chgCData(oldp+229,(vlSelf->mac_top__DOT__u_array__DOT__gen_rows__BRA__1__KET____DOT__gen_cols__BRA__3__KET____DOT__inst_pe__DOT__a_reg),8);
        bufp->chgCData(oldp+230,(vlSelf->mac_top__DOT__u_array__DOT__gen_rows__BRA__1__KET____DOT__gen_cols__BRA__3__KET____DOT__inst_pe__DOT__w_reg),8);
        bufp->chgSData(oldp+231,(vlSelf->mac_top__DOT__u_array__DOT__gen_rows__BRA__1__KET____DOT__gen_cols__BRA__3__KET____DOT__inst_pe__DOT__mul_reg),16);
        bufp->chgCData(oldp+232,(vlSelf->mac_top__DOT__u_array__DOT__h_wire
                                 [2U][0U]),8);
        bufp->chgCData(oldp+233,(vlSelf->mac_top__DOT__u_array__DOT__weight_in
                                 [2U][0U]),8);
        bufp->chgIData(oldp+234,(vlSelf->mac_top__DOT__u_array__DOT__v_wire
                                 [2U][0U]),32);
        bufp->chgCData(oldp+235,(vlSelf->mac_top__DOT__u_array__DOT____Vcellout__gen_rows__BRA__2__KET____DOT__gen_cols__BRA__0__KET____DOT__inst_pe__a_out),8);
        bufp->chgIData(oldp+236,(vlSelf->mac_top__DOT__u_array__DOT____Vcellout__gen_rows__BRA__2__KET____DOT__gen_cols__BRA__0__KET____DOT__inst_pe__acc_out),32);
        bufp->chgCData(oldp+237,(vlSelf->mac_top__DOT__u_array__DOT__gen_rows__BRA__2__KET____DOT__gen_cols__BRA__0__KET____DOT__inst_pe__DOT__a_reg),8);
        bufp->chgCData(oldp+238,(vlSelf->mac_top__DOT__u_array__DOT__gen_rows__BRA__2__KET____DOT__gen_cols__BRA__0__KET____DOT__inst_pe__DOT__w_reg),8);
        bufp->chgSData(oldp+239,(vlSelf->mac_top__DOT__u_array__DOT__gen_rows__BRA__2__KET____DOT__gen_cols__BRA__0__KET____DOT__inst_pe__DOT__mul_reg),16);
        bufp->chgCData(oldp+240,(vlSelf->mac_top__DOT__u_array__DOT__h_wire
                                 [2U][1U]),8);
        bufp->chgCData(oldp+241,(vlSelf->mac_top__DOT__u_array__DOT__weight_in
                                 [2U][1U]),8);
        bufp->chgIData(oldp+242,(vlSelf->mac_top__DOT__u_array__DOT__v_wire
                                 [2U][1U]),32);
        bufp->chgCData(oldp+243,(vlSelf->mac_top__DOT__u_array__DOT____Vcellout__gen_rows__BRA__2__KET____DOT__gen_cols__BRA__1__KET____DOT__inst_pe__a_out),8);
        bufp->chgIData(oldp+244,(vlSelf->mac_top__DOT__u_array__DOT____Vcellout__gen_rows__BRA__2__KET____DOT__gen_cols__BRA__1__KET____DOT__inst_pe__acc_out),32);
        bufp->chgCData(oldp+245,(vlSelf->mac_top__DOT__u_array__DOT__gen_rows__BRA__2__KET____DOT__gen_cols__BRA__1__KET____DOT__inst_pe__DOT__a_reg),8);
        bufp->chgCData(oldp+246,(vlSelf->mac_top__DOT__u_array__DOT__gen_rows__BRA__2__KET____DOT__gen_cols__BRA__1__KET____DOT__inst_pe__DOT__w_reg),8);
        bufp->chgSData(oldp+247,(vlSelf->mac_top__DOT__u_array__DOT__gen_rows__BRA__2__KET____DOT__gen_cols__BRA__1__KET____DOT__inst_pe__DOT__mul_reg),16);
        bufp->chgCData(oldp+248,(vlSelf->mac_top__DOT__u_array__DOT__h_wire
                                 [2U][2U]),8);
        bufp->chgCData(oldp+249,(vlSelf->mac_top__DOT__u_array__DOT__weight_in
                                 [2U][2U]),8);
        bufp->chgIData(oldp+250,(vlSelf->mac_top__DOT__u_array__DOT__v_wire
                                 [2U][2U]),32);
        bufp->chgCData(oldp+251,(vlSelf->mac_top__DOT__u_array__DOT____Vcellout__gen_rows__BRA__2__KET____DOT__gen_cols__BRA__2__KET____DOT__inst_pe__a_out),8);
        bufp->chgIData(oldp+252,(vlSelf->mac_top__DOT__u_array__DOT____Vcellout__gen_rows__BRA__2__KET____DOT__gen_cols__BRA__2__KET____DOT__inst_pe__acc_out),32);
        bufp->chgCData(oldp+253,(vlSelf->mac_top__DOT__u_array__DOT__gen_rows__BRA__2__KET____DOT__gen_cols__BRA__2__KET____DOT__inst_pe__DOT__a_reg),8);
        bufp->chgCData(oldp+254,(vlSelf->mac_top__DOT__u_array__DOT__gen_rows__BRA__2__KET____DOT__gen_cols__BRA__2__KET____DOT__inst_pe__DOT__w_reg),8);
        bufp->chgSData(oldp+255,(vlSelf->mac_top__DOT__u_array__DOT__gen_rows__BRA__2__KET____DOT__gen_cols__BRA__2__KET____DOT__inst_pe__DOT__mul_reg),16);
        bufp->chgCData(oldp+256,(vlSelf->mac_top__DOT__u_array__DOT__h_wire
                                 [2U][3U]),8);
        bufp->chgCData(oldp+257,(vlSelf->mac_top__DOT__u_array__DOT__weight_in
                                 [2U][3U]),8);
        bufp->chgIData(oldp+258,(vlSelf->mac_top__DOT__u_array__DOT__v_wire
                                 [2U][3U]),32);
        bufp->chgCData(oldp+259,(vlSelf->mac_top__DOT__u_array__DOT____Vcellout__gen_rows__BRA__2__KET____DOT__gen_cols__BRA__3__KET____DOT__inst_pe__a_out),8);
        bufp->chgIData(oldp+260,(vlSelf->mac_top__DOT__u_array__DOT____Vcellout__gen_rows__BRA__2__KET____DOT__gen_cols__BRA__3__KET____DOT__inst_pe__acc_out),32);
        bufp->chgCData(oldp+261,(vlSelf->mac_top__DOT__u_array__DOT__gen_rows__BRA__2__KET____DOT__gen_cols__BRA__3__KET____DOT__inst_pe__DOT__a_reg),8);
        bufp->chgCData(oldp+262,(vlSelf->mac_top__DOT__u_array__DOT__gen_rows__BRA__2__KET____DOT__gen_cols__BRA__3__KET____DOT__inst_pe__DOT__w_reg),8);
        bufp->chgSData(oldp+263,(vlSelf->mac_top__DOT__u_array__DOT__gen_rows__BRA__2__KET____DOT__gen_cols__BRA__3__KET____DOT__inst_pe__DOT__mul_reg),16);
        bufp->chgCData(oldp+264,(vlSelf->mac_top__DOT__u_array__DOT__h_wire
                                 [3U][0U]),8);
        bufp->chgCData(oldp+265,(vlSelf->mac_top__DOT__u_array__DOT__weight_in
                                 [3U][0U]),8);
        bufp->chgIData(oldp+266,(vlSelf->mac_top__DOT__u_array__DOT__v_wire
                                 [3U][0U]),32);
        bufp->chgCData(oldp+267,(vlSelf->mac_top__DOT__u_array__DOT____Vcellout__gen_rows__BRA__3__KET____DOT__gen_cols__BRA__0__KET____DOT__inst_pe__a_out),8);
        bufp->chgIData(oldp+268,(vlSelf->mac_top__DOT__u_array__DOT____Vcellout__gen_rows__BRA__3__KET____DOT__gen_cols__BRA__0__KET____DOT__inst_pe__acc_out),32);
        bufp->chgCData(oldp+269,(vlSelf->mac_top__DOT__u_array__DOT__gen_rows__BRA__3__KET____DOT__gen_cols__BRA__0__KET____DOT__inst_pe__DOT__a_reg),8);
        bufp->chgCData(oldp+270,(vlSelf->mac_top__DOT__u_array__DOT__gen_rows__BRA__3__KET____DOT__gen_cols__BRA__0__KET____DOT__inst_pe__DOT__w_reg),8);
        bufp->chgSData(oldp+271,(vlSelf->mac_top__DOT__u_array__DOT__gen_rows__BRA__3__KET____DOT__gen_cols__BRA__0__KET____DOT__inst_pe__DOT__mul_reg),16);
        bufp->chgCData(oldp+272,(vlSelf->mac_top__DOT__u_array__DOT__h_wire
                                 [3U][1U]),8);
        bufp->chgCData(oldp+273,(vlSelf->mac_top__DOT__u_array__DOT__weight_in
                                 [3U][1U]),8);
        bufp->chgIData(oldp+274,(vlSelf->mac_top__DOT__u_array__DOT__v_wire
                                 [3U][1U]),32);
        bufp->chgCData(oldp+275,(vlSelf->mac_top__DOT__u_array__DOT____Vcellout__gen_rows__BRA__3__KET____DOT__gen_cols__BRA__1__KET____DOT__inst_pe__a_out),8);
        bufp->chgIData(oldp+276,(vlSelf->mac_top__DOT__u_array__DOT____Vcellout__gen_rows__BRA__3__KET____DOT__gen_cols__BRA__1__KET____DOT__inst_pe__acc_out),32);
        bufp->chgCData(oldp+277,(vlSelf->mac_top__DOT__u_array__DOT__gen_rows__BRA__3__KET____DOT__gen_cols__BRA__1__KET____DOT__inst_pe__DOT__a_reg),8);
        bufp->chgCData(oldp+278,(vlSelf->mac_top__DOT__u_array__DOT__gen_rows__BRA__3__KET____DOT__gen_cols__BRA__1__KET____DOT__inst_pe__DOT__w_reg),8);
        bufp->chgSData(oldp+279,(vlSelf->mac_top__DOT__u_array__DOT__gen_rows__BRA__3__KET____DOT__gen_cols__BRA__1__KET____DOT__inst_pe__DOT__mul_reg),16);
        bufp->chgCData(oldp+280,(vlSelf->mac_top__DOT__u_array__DOT__h_wire
                                 [3U][2U]),8);
        bufp->chgCData(oldp+281,(vlSelf->mac_top__DOT__u_array__DOT__weight_in
                                 [3U][2U]),8);
        bufp->chgIData(oldp+282,(vlSelf->mac_top__DOT__u_array__DOT__v_wire
                                 [3U][2U]),32);
        bufp->chgCData(oldp+283,(vlSelf->mac_top__DOT__u_array__DOT____Vcellout__gen_rows__BRA__3__KET____DOT__gen_cols__BRA__2__KET____DOT__inst_pe__a_out),8);
        bufp->chgIData(oldp+284,(vlSelf->mac_top__DOT__u_array__DOT____Vcellout__gen_rows__BRA__3__KET____DOT__gen_cols__BRA__2__KET____DOT__inst_pe__acc_out),32);
        bufp->chgCData(oldp+285,(vlSelf->mac_top__DOT__u_array__DOT__gen_rows__BRA__3__KET____DOT__gen_cols__BRA__2__KET____DOT__inst_pe__DOT__a_reg),8);
        bufp->chgCData(oldp+286,(vlSelf->mac_top__DOT__u_array__DOT__gen_rows__BRA__3__KET____DOT__gen_cols__BRA__2__KET____DOT__inst_pe__DOT__w_reg),8);
        bufp->chgSData(oldp+287,(vlSelf->mac_top__DOT__u_array__DOT__gen_rows__BRA__3__KET____DOT__gen_cols__BRA__2__KET____DOT__inst_pe__DOT__mul_reg),16);
        bufp->chgCData(oldp+288,(vlSelf->mac_top__DOT__u_array__DOT__h_wire
                                 [3U][3U]),8);
        bufp->chgCData(oldp+289,(vlSelf->mac_top__DOT__u_array__DOT__weight_in
                                 [3U][3U]),8);
        bufp->chgIData(oldp+290,(vlSelf->mac_top__DOT__u_array__DOT__v_wire
                                 [3U][3U]),32);
        bufp->chgCData(oldp+291,(vlSelf->mac_top__DOT__u_array__DOT____Vcellout__gen_rows__BRA__3__KET____DOT__gen_cols__BRA__3__KET____DOT__inst_pe__a_out),8);
        bufp->chgIData(oldp+292,(vlSelf->mac_top__DOT__u_array__DOT____Vcellout__gen_rows__BRA__3__KET____DOT__gen_cols__BRA__3__KET____DOT__inst_pe__acc_out),32);
        bufp->chgCData(oldp+293,(vlSelf->mac_top__DOT__u_array__DOT__gen_rows__BRA__3__KET____DOT__gen_cols__BRA__3__KET____DOT__inst_pe__DOT__a_reg),8);
        bufp->chgCData(oldp+294,(vlSelf->mac_top__DOT__u_array__DOT__gen_rows__BRA__3__KET____DOT__gen_cols__BRA__3__KET____DOT__inst_pe__DOT__w_reg),8);
        bufp->chgSData(oldp+295,(vlSelf->mac_top__DOT__u_array__DOT__gen_rows__BRA__3__KET____DOT__gen_cols__BRA__3__KET____DOT__inst_pe__DOT__mul_reg),16);
        bufp->chgBit(oldp+296,(vlSelf->mac_top__DOT__u_regs__DOT__sticky_done));
        bufp->chgCData(oldp+297,(vlSelf->mac_top__DOT__u_regs__DOT__pe_addr_reg),4);
    }
    bufp->chgBit(oldp+298,(vlSelf->clk));
    bufp->chgBit(oldp+299,(vlSelf->rst_n));
    bufp->chgIData(oldp+300,(vlSelf->paddr),32);
    bufp->chgBit(oldp+301,(vlSelf->psel));
    bufp->chgBit(oldp+302,(vlSelf->penable));
    bufp->chgBit(oldp+303,(vlSelf->pwrite));
    bufp->chgIData(oldp+304,(vlSelf->pwdata),32);
    bufp->chgIData(oldp+305,(vlSelf->prdata),32);
    bufp->chgBit(oldp+306,(vlSelf->pready));
    bufp->chgBit(oldp+307,(vlSelf->done_o));
    bufp->chgCData(oldp+308,(vlSelf->fsm_state_o),3);
    bufp->chgBit(oldp+309,(vlSelf->m_req_o));
    bufp->chgBit(oldp+310,(vlSelf->m_gnt_i));
    bufp->chgIData(oldp+311,(vlSelf->m_addr_o),32);
    bufp->chgBit(oldp+312,(vlSelf->m_we_o));
    bufp->chgIData(oldp+313,(vlSelf->m_wdata_o),32);
    bufp->chgBit(oldp+314,(vlSelf->m_rvalid_i));
    bufp->chgIData(oldp+315,(vlSelf->m_rdata_i),32);
    bufp->chgIData(oldp+316,(vlSelf->result_hold_o_0),32);
    bufp->chgIData(oldp+317,(vlSelf->result_hold_o_1),32);
    bufp->chgIData(oldp+318,(vlSelf->result_hold_o_2),32);
    bufp->chgIData(oldp+319,(vlSelf->result_hold_o_3),32);
    bufp->chgCData(oldp+320,(vlSelf->mac_top__DOT__next_state),4);
}

void Vmac_top___024root__trace_cleanup(void* voidSelf, VerilatedVcd* /*unused*/) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vmac_top___024root__trace_cleanup\n"); );
    // Init
    Vmac_top___024root* const __restrict vlSelf VL_ATTR_UNUSED = static_cast<Vmac_top___024root*>(voidSelf);
    Vmac_top__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    // Body
    vlSymsp->__Vm_activity = false;
    vlSymsp->TOP.__Vm_traceActivity[0U] = 0U;
    vlSymsp->TOP.__Vm_traceActivity[1U] = 0U;
}
