"""`gli-flow demo` — scaffold a runnable example design in the current folder.

After a global `pip install gli-flow`, the student doesn't have the repo's
examples/ directory. This command writes a self-contained counter design
(RTL + SDC + manifest) into ./gli-demo/counter so they can immediately run:

    gli-flow demo
    gli-flow run gli-demo/counter --mock
"""

from __future__ import annotations

import os
from pathlib import Path

from gli_flow.cli.utils import success, info, warn


COUNTER_V = """module counter (
    input  wire clk,
    input  wire reset,
    output reg  [7:0] count
);

    always @(posedge clk or posedge reset) begin
        if (reset)
            count <= 8'b0;
        else
            count <= count + 1'b1;
    end

endmodule
"""

COUNTER_SDC = """create_clock -name clk -period 10.000 [get_ports clk]
set_input_delay -clock clk 2.0 [get_ports reset]
set_output_delay -clock clk 2.0 [get_ports count]
set_load 0.05 [all_outputs]
"""

# Manifest uses paths relative to the design dir so it works wherever the
# student scaffolds it.
MANIFEST_YAML = """design_name: counter
rtl_files:
  - counter.v
top_module: counter
backend: openroad
pdk: sky130
pdk_variant: sky130A
clock_port: clk
clock_period_ns: 10.0
constraints:
  - counter.sdc
threads: 4
corners:
  - name: worst
    type: worst
    process: slow
    voltage: 1.62
    temperature: 125
  - name: typical
    type: typical
    process: typical
    voltage: 1.80
    temperature: 25
  - name: best
    type: best
    process: fast
    voltage: 1.95
    temperature: -40
"""

README = """# Counter demo (generated by `gli-flow demo`)

A simple 8-bit up-counter. Run it with:

    gli-flow run gli-demo/counter --mock

Remove the `--mock` flag to run the real EDA toolchain (requires the
toolchain installed via `gli-flow install`).
"""


def demo_command(args):
    target_root = Path(getattr(args, "path", None) or "gli-demo").resolve()
    design_dir = target_root / "counter"
    design_dir.mkdir(parents=True, exist_ok=True)

    files = {
        "counter.v": COUNTER_V,
        "counter.sdc": COUNTER_SDC,
        "gli_manifest.yaml": MANIFEST_YAML,
        "README.md": README,
    }

    wrote = 0
    for name, content in files.items():
        dest = design_dir / name
        if dest.exists() and not getattr(args, "force", False):
            warn(f"exists, skipping: {dest.relative_to(Path.cwd()) if str(dest).startswith(str(Path.cwd())) else dest}")
            continue
        dest.write_text(content)
        wrote += 1

    success(f"Demo design ready at {design_dir}")
    info(f"  Wrote {wrote} file(s).")
    info("")
    info("Next:")
    info(f"  gli-flow run {os.path.relpath(design_dir)} --mock")
